### ISSUE TITLE
Is there a reason not all channels show in sidebar?

### ISSUE THREAD

**Issue by nikivdev** [agentcooper/Telik#1]
<img width="201" alt="image" src="https://user-images.githubusercontent.com/6391776/171646126-85418d57-61ad-4629-a0e7-1febf2f397b6.png">

My list stops here. So over 1,000 channels get left out for me. :(

Perhaps when I went to https://www.youtube.com/feed/channels it didn't get all channels.

**Comment by agentcooper** [comment]
@nikitavoloboev Yeah, I wonder if the JS script for extracting the channels from the website accounts for the lazy loading. It would be great if you can check that.

**Comment by nikivdev** [comment]
It's strange. The line you see after `Ali Spittel` channel is the cutting point for lazy loading the next page.

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/6391776/171659309-598488e2-0fad-4757-ba4a-0b2db5266af9.png">

But this is my sidebar now:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/6391776/171659351-888b2f15-b0f0-4db9-b9f9-d9b19f866040.png">

But yes there is lazy loading on the page and it doesn't account for it. 

I guess solution is to lazy load the entire page and then run the script?

**Comment by agentcooper** [comment]
Yes, please try to load the whole page and then run the script. If you can come up with the script that does it automatically, I would gladly accept the PR :-)

Also I'll update the channel title sorting to be case independent as it is on youtube.com.

**Comment by nikivdev** [comment]
![image](https://user-images.githubusercontent.com/6391776/171664994-c47653cf-cf28-4f78-bb4c-e6c499a5451e.jpeg)

Been like this for 20+ min now. Not sure if stuck or I should wait more.

**Comment by nikivdev** [comment]
Okay stopping it now as I need to use the mac. But 20+ min it was stuck on the beach ball and the app is not responsive now so will close it from activity monitor. 

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6391776/171667594-ff1e74e7-eb4f-4158-bb2b-8b5c0bb9ccac.png">

**Comment by nikivdev** [comment]
Here is a gist of all my YouTube follows if you want to replicate it. ♥️

https://gist.github.com/nikitavoloboev/d7d179271bc2f63f02f6b24b29c307bb

**Comment by nikivdev** [comment]
Oh interesting thing after quitting the app during it trying to add channels. If I open the app again, after like a second it starts not responding again and beach balls. 

<img width="418" alt="image" src="https://user-images.githubusercontent.com/6391776/171668981-f72d4f37-527a-402e-91a0-46b3888d3ce2.png">

**Comment by agentcooper** [comment]
Thanks, I'll take a look! When adding channels, there are few URL formats, some contain channel ID and others don't. In the latter case I need to do an additional request. The problem right now that those are sequential and probably error handling is not very good.

For the case when the channels are already added, I think the problem is unbounded concurrency for network calls. I'll try to limit it.

Feel free to drop more feedback on https://t.me/random_internet_username.

**Comment by agentcooper** [comment]
I've released https://github.com/agentcooper/Telik/releases/tag/1.4 and it should perform much better on large lists, please try it out.
