### ISSUE TITLE
$VideoID in addition to $URL

### ISSUE THREAD

**Issue by noestreich** [agentcooper/Telik#12]
Thanks for developing Telik, I really appreciate the app! I have a feature-request. 

It would be great if the "Custom URL"-Option would offer a variable for YouTubes $VideoID.

So one could easily use alternativ frontends like [INVIDIOUS](https://yewtu.be/) with "Custom URL" an
[https://yewtu.be/watch?v=$VideoID](https://yewtu.be/watch?v=Cqd1Gvq-RBY)

Right now i can use 
[https://yewtu.be/search?q=$URL](https://yewtu.be/search?q=https://www.youtube.com/watch?v=Cqd1Gvq-RBY) as a workaround and have to click just once more, but a variable for the ID would make it seamless.

**Comment by agentcooper** [comment]
Thanks for suggestion, done in [1.10](https://github.com/agentcooper/Telik/releases/tag/1.10).
