### ISSUE TITLE
Doesn't add channels

### ISSUE THREAD

**Issue by olegkron** [agentcooper/Telik#13]
Feeding the links in the following format, getting an empty list of channels as a result. Using last version 1.10

- [a16z crypto](https://www.youtube.com/@a16zcrypto)
....

**Comment by agentcooper** [comment]
Thanks for the bug report, fixed in [1.11](https://github.com/agentcooper/Telik/releases/tag/1.11).

**Comment by olegkron** [comment]
Wow, that was quick! Thank you so much!!
