### ISSUE TITLE
Add ability to jump to a YouTube channel from command palette search

### ISSUE THREAD

**Issue by nikivdev** [agentcooper/Telik#2]
This app is incredible, thanks for making it.

One thing that'd be awesome to have a hotkey to trigger a search bar that will jump to a specific channel.

**Comment by agentcooper** [comment]
Thanks for trying it out!

I did not find a way to focus on the search bar in SwiftUI through a shortcut, so maybe I'll do a custom UI for this.

**Comment by agentcooper** [comment]
Released in https://github.com/agentcooper/Telik/releases/tag/1.4.
