### ISSUE TITLE
Add ability to create 'Subscription groups'

### ISSUE THREAD

**Issue by nikivdev** [agentcooper/Telik#3]
That would be a killer feature for me. I would like to be able to group some channels into a group, say 'News' that includes 5 channels. Going to the group then will show a subscription feed for only the channels in the group. Similar to what you get now but for ALL the channels.

I may try to get this working but new to Swift. 😺

**Comment by agentcooper** [comment]
Isn't this the same as tags? You can right click the channel (multiple selection with ⌘/⇧ works as well) and add a tag, then the list of tags will appear under "All channels". Selecting the tag shows all videos from channels with this particular tag.

**Comment by nikivdev** [comment]
Amazing, that's exactly what I was looking for. ♥️
