### ISSUE TITLE
Allow custom names for channels 

### ISSUE THREAD

**Issue by nikivdev** [agentcooper/Telik#4]
The use case I have is that I have a bunch of Russian channels I sub to and I'd love to quickly jump to them with new cmd+O feature.

But if you search for say:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/6391776/172067510-874d7e2b-b739-42c8-b18e-d65ddfb313d3.png">

It won't return any results because it needs to be in Russian.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/6391776/172067524-139f0d92-93bc-4776-a6dd-a184de79c4b9.png">

Not sure how feasible it is to implement but would be nice. ♥️

**Comment by agentcooper** [comment]
Good suggestion, thank you! Instead of custom names I made it work with built-in latin transliteration, so your example with "vdud" will show both channels now.

Done in https://github.com/agentcooper/Telik/commit/cc9ba1bc9f38657d6813e76db69b42ac8ee4881f, released in https://github.com/agentcooper/Telik/releases/tag/1.5.

**Comment by nikivdev** [comment]
This is a very nice change, thank you.

One thing that it does bring is a regression in speed. On my list of subscriptions if I type `vd` really fast, the first `v` will bring results quite fast but after typing `d` it would lag and only update the search input after ~ 2 seconds. And that's on latest M1 mac.

I'll try to look into the issue as I am certain this is only an issue when you have as many subscriptions as me which few will have. 😄

Also it's not that much of an issue but would be nice to get instant feedback on searches. Perhaps by creating an index with SQLite and doing a search on that. Not sure how it's currently done.

**Comment by agentcooper** [comment]
I didn't see much lag when testing with many channels, but I think there is clearly room for improvement.

It would be cool if you can try to optimize it. Right now it is mostly a dumb loop through the whole list with caching only for the transliteration results.

Maybe the search needs to become async and debounced.
