### ISSUE TITLE
Add option to open in custom player

### ISSUE THREAD

**Issue by sermelipharo** [agentcooper/Telik#7]
Currently all options to open videos requires to bring up browser window. How about adding option to enter custom uri-scheme/shell command/etc. or just support for different players, e.g. [iina](https://github.com/iina/iina)

**Comment by agentcooper** [comment]
@sermelipharo Yeah, I think it is a good option. Do you have an example command that would start a YouTube video in IINA? Do you have other apps in mind?

**Comment by sermelipharo** [comment]
I guess as we're on macOS there will be enough just to use pattern `open -a $APPNAME $URL`, e.g. `open -a IINA https://youtu.be/ask2wLNeAQg`

iina, [yt-dlp](https://github.com/yt-dlp/yt-dlp), [mps-youtube -> mpv](https://github.com/mps-youtube/mps-youtube)

**Comment by nicohansi** [comment]
I would also love a feature like this.

**Comment by agentcooper** [comment]
I implemented this in version 1.9.

It is not possible to keep app sandbox and allow custom shell commands, so only custom URLs are supported. For IINA you can use `iina://weblink?url=$URL`.

If you want to run a custom shell command, you can create a shortcut that runs the command and then use shortcut URL: https://support.apple.com/en-gb/guide/shortcuts/apd624386f42/6.0/ios/16.0.

Feel free to reopen if you have any issues or comments.
