### ISSUE TITLE
Can we get all Videos from Added Channel?

### ISSUE THREAD

**Issue by shrtinfo** [agentcooper/Telik#9]
Great App.

I added on youtube channel , but it fetching only few items.
How can we get all videos?

Thanks

**Comment by agentcooper** [comment]
Hey, thanks!

This app relies on RSS feeds that YouTube provides and they have a limit on videos. You can get feed url with the right click on the channel in the sidebar (Copy feed URL).

If you think that the feed URL has more videos than shown in the app, please reopen this issue.
